name: "scrumbot"

base_url: https://ayfie-dev.atlassian.net
start_message: "It's time for the weekly estimation!
Please provide a fibonacci-number estimation for the following tasks:"




teams:
  professional-services:
    allowed_responses: ["0","1","2","3","5","8","13","21","34","55","100"]
    users_to_notify:
      - trevortds@gmail.com
    # when you want users to start getting questions
    start_time:
      day_of_week: Tuesday
      time: 11 AM
      time_zone: America/New_York
    # When you want to stop accepting answers and put the responses in the channel.
    end_time:
      day_of_week: Tuesday
      time: 3 PM
      time_zone: America/New_York
    max_per_meeting: 10
    meeting_channel: "general"
    jql_search_query: 'project in (PSE, "IN", CQRC, Bahr) AND cf[10022] = "OPS America" AND status = "To Do" AND type != Epic AND "Story Points" is EMPTY ORDER BY createdDate ASC'