"""added conversations

Revision ID: 09704addc4e7
Revises: 15f6b2caa3fa
Create Date: 2018-08-23 11:15:27.020943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09704addc4e7'
down_revision = '15f6b2caa3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=False)
    op.create_index(op.f('ix_issues_team'), 'issues', ['team'], unique=False)
    op.add_column('user', sa.Column('awaiting_response', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('conversation', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'conversation')
    op.drop_column('user', 'awaiting_response')
    op.drop_index(op.f('ix_issues_team'), table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
