"""renamed issues to issue

Revision ID: de97779f2de9
Revises: 09704addc4e7
Create Date: 2018-08-23 15:27:02.164093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de97779f2de9'
down_revision = '09704addc4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_key'), 'issue', ['key'], unique=False)
    op.create_index(op.f('ix_issue_team'), 'issue', ['team'], unique=False)
    op.drop_index('ix_issues_key', table_name='issues')
    op.drop_index('ix_issues_team', table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team', sa.VARCHAR(length=64), nullable=True),
    sa.Column('key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('summary', sa.VARCHAR(length=256), nullable=True),
    sa.Column('url', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_team', 'issues', ['team'], unique=False)
    op.create_index('ix_issues_key', 'issues', ['key'], unique=False)
    op.drop_index(op.f('ix_issue_team'), table_name='issue')
    op.drop_index(op.f('ix_issue_key'), table_name='issue')
    op.drop_table('issue')
    # ### end Alembic commands ###
