"""added value to answers

Revision ID: ec56ecd55282
Revises: de97779f2de9
Create Date: 2018-08-23 16:10:20.569963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec56ecd55282'
down_revision = 'de97779f2de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('value', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'value')
    # ### end Alembic commands ###
